#!/bin/sh

# shebang for coloration, this should only be sourced

class() {
  local name="$1"
  shift
  local init=
  local object_body=
  local class_body="$name() {"
  local attr_index=2
  local nb_args="$#"
  while [ "$nb_args" -gt 0 ]; do
    case "$1" in
      _*)
        set -- "$@" "$1"
        ;;
      *)
          object_body="$object_body      $1"')
        if [ "$#" -gt 1 ]; then
          if [ "$2" = = ]; then
            if [ "$#" -gt 3 ]; then
              var _'"'"'"$1"'"'"'_'"$1"' = "$@"
            else
              _'"'"'"$1"'"'"'_'"$1"'="$3"
            fi
          else
            shift
            "$_'"'"'"$1"'"'"'_'"$1"'" "$@"
          fi
        else
          var="$_'"'"'"$1"'"'"'_'"$1"'"
        fi
        ;;'
          init="$init"'
  eval _"$1"'"_$1"'='"'"'${'"$attr_index"'}'"'"
          attr_index="$((attr_index + 1))"
        ;;
    esac
    nb_args="$((nb_args - 1))"
    shift
  done

  for method do
    object_body="$object_body"'
      '"${method#_}"')
        shift
        '"$name$method"' '"'"'"$1"'"'"' "$@"
        ;;'
  done
  object_body='
  eval "$1"'"'"'() {
    case "$1" in
'"$object_body"'
    esac
  }'"'"
  class_body="$class_body$object_body$init"

  class_body="$class_body"'
}'

  eval "$class_body"
}

var() {
  local varname="$1"
  shift 2
  local var=
  "$@"
  eval "$varname"='$var'
  unset var varname
}

_unpack_helper() {
  while true; do
    if [ "$1" = = ]; then
      break
    fi
    shift
  done
  var "$attr_name" "$@" "$attr_name" 
}

unpack() {
  local attr_name=
  for attr_name do
    if [ "$attr_name" = = ]; then
      break
    fi
    _unpack_helper "$@"
    shift
  done
}
